name: editing file

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
    steps:
      - name:
        run: echo "this is something"
      - name: readmeupdate
        run: echo "hi there" >> README.md
